
networks:
  nooble-network:
    driver: bridge

services:
  redis:
    networks:
      - nooble-network
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    networks:
      - nooble-network
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  query_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./query_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - qdrant
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  agent_orchestrator_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_orchestrator_service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  ingestion_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./ingestion_service/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - qdrant
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env


  conversation_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./conversation_service/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - redis
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  agent_execution_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_execution_service/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - redis
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  embedding_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./embedding_service/Dockerfile
    ports:
      - "8006:8006"
    depends_on:
      - redis
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

volumes:
  redis_data:
  qdrant_data:
