networks:
  nooble-network:
    driver: bridge

services:
  redis_database:
    networks:
      - nooble-network
    build:
      context: ./redis_database
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant_database:
    networks:
      - nooble-network
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    networks:
      - nooble-network
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_database/init:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  query_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./query_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis_database
      - qdrant_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  agent_orchestrator_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_orchestrator_service/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  ingestion_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./ingestion_service/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - redis_database
      - qdrant_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  conversation_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./conversation_service/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - redis_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  agent_execution_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_execution_service/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - redis_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  embedding_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./embedding_service/Dockerfile
    ports:
      - "8006:8006"
    depends_on:
      - redis_database
    volumes:
      - ./common:/app/common
    env_file:
      - ./.env

  keycloak:
    networks:
      - nooble-network
    build:
      context: ./keycloak_auth
      dockerfile: Dockerfile
    container_name: nooble4-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_auth/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - keycloak_data:/opt/keycloak/data

  kong-migrations:
    build:
      context: ./kong_gateway
      dockerfile: kong.Dockerfile
    container_name: nooble4-kong-migrations
    networks:
      - nooble-network
    command: "kong migrations bootstrap"
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PG_DATABASE: kong
    restart: on-failure
    env_file:
      - ./.env

  kong:
    build:
      context: ./kong_gateway
      dockerfile: kong.Dockerfile
    container_name: nooble4-kong-gateway
    networks:
      - nooble-network
    depends_on:
      - kong-migrations
    environment:
      # The password is the only variable needed now, as it's injected into kong.conf
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
    ports:
      - "8081:8000" # Proxy HTTP
      - "8443:8443" # Proxy HTTPS
      - "8011:8001" # Admin API
      - "8454:8444" # Admin API SSL
    restart: always
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    env_file:
      - ./.env

  konga:
    build:
      context: ./kong_gateway
      dockerfile: konga.Dockerfile
    container_name: nooble4-konga
    networks:
      - nooble-network
    depends_on:
      - kong
    environment:
      NODE_ENV: development
      KONGA_KONG_URL: http://kong:8001
    ports:
      - "1337:1337"
    restart: always

volumes:
  redis_data:
  qdrant_data:
  postgres_data:
  keycloak_data: