version: "3.8"

networks:
  nooble-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  # ===========================================
  # Bases de Datos
  # ===========================================
  
  redis_database:
    image: redis:7-alpine
    container_name: redis_database
    networks:
      - nooble-network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  qdrant_database:
    networks:
      - nooble-network
    image: qdrant/qdrant:v1.7.4
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    env_file:
      - ./qdrant_database/.env
    environment:
      - QDRANT_HOST=${QDRANT_HOST:-0.0.0.0}
      - QDRANT_HTTP_PORT=${QDRANT_HTTP_PORT:-6333}
      - QDRANT_GRPC_PORT=${QDRANT_GRPC_PORT:-6334}
      - QDRANT_STORAGE_PATH=/qdrant/storage
    volumes:
      - qdrant_data:/qdrant/storage
      - ./qdrant_database/config:/qdrant/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres_database:
    build:
      context: ./postgres_database
      dockerfile: Dockerfile
    container_name: postgres_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nooble}
      # Custom data directory to avoid conflicts
      PGDATA: /var/lib/postgresql/data/pgdata
      # Add these environment variables for the initialization script
      POSTGRES_INITDB_ARGS: "--data-checksums --encoding=UTF8"
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/data/pg_wal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${AUTHENTIK_POSTGRESQL_NAME:-authentik}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    ports:
      - "5432:5432"
    networks:
      - nooble-network
    # Add restart policy
    restart: unless-stopped

  # ===========================================
  # Servicios de Autenticación
  # ===========================================

  authentik_server:
    build:
      context: ./authentik_auth
      dockerfile: Dockerfile
    container_name: authentik_server
    restart: unless-stopped
    networks:
      - nooble-network
    depends_on:
      postgres_database:
        condition: service_healthy
      redis_database:
        condition: service_healthy
    env_file:
      - ./authentik_auth/.env
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=postgres_database
      - AUTHENTIK_REDIS__HOST=redis_database
      - AUTHENTIK_REDIS__PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - ./authentik_auth/media:/media
      - ./authentik_auth/certs:/certs
      - ./authentik_auth/custom-templates:/templates
      - ./authentik_auth/blueprints:/etc/authentik/blueprints
      - ./authentik_auth/policies:/etc/authentik/policies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/-/health/live/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  authentik_worker:
    build:
      context: ./authentik_auth
      dockerfile: Dockerfile
    container_name: authentik_worker
    command: worker
    restart: unless-stopped
    networks:
      - nooble-network
    depends_on:
      postgres_database:
        condition: service_healthy
      redis_database:
        condition: service_healthy
    env_file:
      - ./authentik_auth/.env
    environment:
      # Solo sobreescribir las variables que necesitan valores específicos del entorno
      - AUTHENTIK_POSTGRESQL__HOST=postgres_database
      - AUTHENTIK_REDIS__HOST=redis_database
      - AUTHENTIK_REDIS__PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - ./authentik_auth/media:/media
      - ./authentik_auth/certs:/certs
      - ./authentik_auth/custom-templates:/templates
      - ./authentik_auth/blueprints:/etc/authentik/blueprints
      - ./authentik_auth/policies:/etc/authentik/policies

  # ===========================================
  # Microservicios de la Aplicación
  # ===========================================

  query_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./query_service/Dockerfile
    expose:
      - "8000"
    depends_on:
      redis_database:
        condition: service_healthy
      qdrant_database:
        condition: service_healthy
      postgres_database:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - QDRANT_URL=http://${QDRANT_HOST:-qdrant_database}:${QDRANT_HTTP_PORT:-6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    volumes:
      - ./common:/app/common:ro
      - ./qdrant_database/.env:/app/.env.qdrant:ro
    env_file:
      - ./.env
      - ./qdrant_database/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  agent_orchestrator_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_orchestrator_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=1
    depends_on:
      redis_database:
        condition: service_healthy
      postgres_database:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orchestrator.rule=PathPrefix(`/orchestrator`)"
      - "traefik.http.routers.orchestrator.entrypoints=websecure"
      - "traefik.http.routers.orchestrator.tls=true"
      - "traefik.http.routers.orchestrator.tls.certresolver=letsencrypt"
      - "traefik.http.routers.orchestrator.middlewares=auth-forward,strip-orchestrator"
      - "traefik.http.services.orchestrator.loadbalancer.server.port=8001"
    volumes:
      - ./common:/app/common:ro
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  ingestion_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./ingestion_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=2
      - QDRANT_URL=http://${QDRANT_HOST:-qdrant_database}:${QDRANT_HTTP_PORT:-6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      redis_database:
        condition: service_healthy
      qdrant_database:
        condition: service_healthy
      postgres_database:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ingestion.rule=PathPrefix(`/ingestion`)"
      - "traefik.http.routers.ingestion.entrypoints=websecure"
      - "traefik.http.routers.ingestion.tls=true"
      - "traefik.http.routers.ingestion.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ingestion.middlewares=auth-forward,strip-ingestion"
      - "traefik.http.services.ingestion.loadbalancer.server.port=8002"
    volumes:
      - ./common:/app/common:ro
      - ./ingestion_data:/tmp/nooble4_ingestion_storage
      - ./qdrant_database/.env:/app/.env.qdrant:ro
    env_file:
      - ./.env
      - ./qdrant_database/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  conversation_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./conversation_service/Dockerfile
    expose:
      - "8004"
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=3
    depends_on:
      redis_database:
        condition: service_healthy
      postgres_database:
        condition: service_healthy
    volumes:
      - ./common:/app/common:ro
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  agent_execution_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./agent_execution_service/Dockerfile
    expose:
      - "8005"
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=4
    depends_on:
      redis_database:
        condition: service_healthy
      postgres_database:
        condition: service_healthy
    volumes:
      - ./common:/app/common:ro
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  embedding_service:
    networks:
      - nooble-network
    build:
      context: .
      dockerfile: ./embedding_service/Dockerfile
    expose:
      - "8006"
    environment:
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=5
    depends_on:
      redis_database:
        condition: service_healthy
    volumes:
      - ./common:/app/common:ro
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # agent_management_service has been renamed to user_management_service but is not ready yet
  # user_management_service:
  #   networks:
  #     - nooble-network
  #   build:
  #     context: .
  #     dockerfile: ./user_management_service/Dockerfile
  #   expose:
  #     - "8003"
  #   depends_on:
  #     redis_database:
  #       condition: service_healthy
  #     postgres_database:
  #       condition: service_healthy
  #   volumes:
  #     - ./common:/app/common:ro
  #   env_file:
  #     - ./.env
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

# ===========================================
# Herramientas de Monitoreo (Opcional)
# ===========================================

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    networks:
      - nooble-network
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    profiles: ["monitoring"]

  # Grafana para visualización
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    networks:
      - nooble-network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://grafana.${BASE_DOMAIN}
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: unless-stopped
    profiles: ["monitoring"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${BASE_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # Jaeger para tracing distribuido
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    networks:
      - nooble-network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    profiles: ["monitoring"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.${BASE_DOMAIN}`)"
      - "traefik.http.routers.jaeger.entrypoints=websecure"
      - "traefik.http.routers.jaeger.tls=true"
      - "traefik.http.routers.jaeger.tls.certresolver=letsencrypt"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
      - "traefik.http.routers.jaeger.middlewares=auth-forward"

# ===========================================
# Volúmenes adicionales para monitoreo
# ===========================================
volumes:

  redis_data:
  qdrant_data:
  postgres_data:
