# Usar la imagen oficial de Redis como base
FROM redis:7.2-alpine

# Opcional: Copiar un archivo de configuración personalizado.
# Descomenta las siguientes líneas si tienes un redis.conf personalizado.
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
