# Configuración principal de Traefik
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Configuración de logs
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json

# Logs de acceso
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

# API y Dashboard
api:
  dashboard: true
  debug: true
  insecure: true # Solo para desarrollo, en producción usar auth

# Puntos de entrada
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  
  # Puerto para métricas
  metrics:
    address: ":8082"

# Proveedores
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: nooble-network
    watch: true
  
  file:
    directory: /etc/traefik/dynamic
    watch: true

# Configuración de certificados SSL (para producción)
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@nooble.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web
      # Para desarrollo/staging
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# Métricas
metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true
    addEntryPointsLabels: true
    addRoutersLabels: true

# Ping endpoint para health checks
ping:
  entryPoint: web

# Tracing (opcional)
# tracing:
#   serviceName: traefik
#   spanNameLimit: 0
#   jaeger:
#     samplingServerURL: http://jaeger:5778/sampling
#     localAgentHostPort: jaeger:6831