# Qdrant Configuration - Base Configuration (Versioned)
# Environment variables take precedence over these values

# Server configuration
service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  max_request_size_mb: 32
  enable_metrics: true
  metrics_address: "0.0.0.0:9090"
  enable_cors: false  # Override in local.yaml if needed

# Logging configuration - can be overridden in local.yaml
log_level: INFO

# Storage configuration
storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  on_disk_payload: true  # Saves RAM by storing payload on disk
  
  # WAL configuration
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0
    recover_virtual_consistency: true

# Performance tuning
performance:
  # Auto-detect number of threads (0 = auto)
  max_search_threads: 0
  max_optimization_threads: 2

# Optimizer configuration
optimizers:
  deleted_threshold: 0.2
  vacuum_min_vector_number: 1000
  default_segment_number: 2
  flush_interval_sec: 5
  max_optimization_threads: 2
  memmap_threshold_kb: 1024
  indexing_threshold_kb: 20000
  
  # HNSW index configuration (for vector search)
  hnsw_config:
    m: 16                # Number of connections per node (16-64)
    ef_construct: 100    # Size of the dynamic list (100-400)
    full_scan_threshold: 10000  # Threshold for sequential scan
    max_indexing_threads: 0  # 0 = auto
    on_disk: false

# Default collection configuration
collection:
  vectors:
    size: 1536  # Default for OpenAI embeddings
    distance: Cosine
    on_disk: false  # Store vectors in memory for better performance
  
  # Shard configuration (for distributed mode)
  shard_number: 1
  replication_factor: 1
  write_consistency_factor: 1

# Cluster configuration (disabled in single-node setup)
cluster:
  enabled: false

# Telemetry (anonymous usage statistics)
telemetry_disabled: false
