# kong.yml configuration
services:
- name: agent-orchestrator
  url: http://orchestrator:8001
  
routes:
- name: chat-routes
  service: agent-orchestrator
  paths: ["/api/chat", "/ws"]
  
plugins:
- name: openid-connect
  service: agent-orchestrator
  config:
    issuer: "http://keycloak:8080/auth/realms/master"
    client_id: "agent-platform"
    client_secret: "secret"
    bearer_token_param_type: ["header", "query"]
    headers_claims: ["tenant_id", "agent_id", "sub"]
    headers_names: ["X-Tenant-ID", "X-Agent-ID", "X-User-ID"]