# authentik_auth/Dockerfile

# Usar la última versión estable de Authentik
FROM ghcr.io/goauthentik/server:latest

# Copiar configuración YAML
COPY config/ /authentik/config/

# Mantener el punto de entrada por defecto
