# authentik_auth/Dockerfile

FROM ghcr.io/goauthentik/server:2025.6

# Copiamos configuración si es necesario
# (puede estar vacía inicialmente)
COPY config/ /config/

# Punto de entrada por defecto (no lo cambiamos)
