# Configuración de Authentik
# Este archivo debe estar en /authentik/config/configuration.yml

# Configuración de PostgreSQL
postgresql:
  host: ${AUTHENTIK_POSTGRESQL__HOST:-postgres_database}
  port: ${AUTHENTIK_POSTGRESQL__PORT:-5432}
  name: ${AUTHENTIK_POSTGRESQL__NAME:-authentik}
  user: ${AUTHENTIK_POSTGRESQL__USER:-authentik_user}
  password: ${AUTHENTIK_POSTGRESQL__PASSWORD:-authentik_pass}
  sslmode: ${AUTHENTIK_POSTGRESQL_SSLMODE:-disable}

# Configuración de Redis
redis:
  host: ${AUTHENTIK_REDIS__HOST:-redis_database}
  port: ${AUTHENTIK_REDIS__PORT:-6379}
  password: ${AUTHENTIK_REDIS__PASSWORD:-}
  db: ${AUTHENTIK_REDIS__DB:-0}
  tls: ${AUTHENTIK_REDIS__TLS:false}
  tls_reqs: ${AUTHENTIK_REDIS__TLS_REQS:verify-full}

# Configuración del servidor web
server:
  port: ${AUTHENTIK_PORT_HTTP:-9000}
  port_https: ${AUTHENTIK_PORT_HTTPS:-9443}
  listen: ${AUTHENTIK_LISTEN:-0.0.0.0}
  domain: ${AUTHENTIK_SERVER__EXTERNAL_HOSTNAME:-localhost}
  external_scheme: ${AUTHENTIK_SERVER__EXTERNAL_SCHEME:-https}
  insecure: ${AUTHENTIK_INSECURE:-false}

# Configuración de errores y logs
error_reporting:
  enabled: ${AUTHENTIK_ERROR_REPORTING__ENABLED:-false}
  environment: ${AUTHENTIK_ENV:-production}
  send_pii: ${AUTHENTIK_ERROR_REPORTING_SEND_PII:-false}

# Configuración de email (ajustar según tu proveedor)
email:
  host: ${AUTHENTIK_EMAIL__HOST:-smtp.gmail.com}
  port: ${AUTHENTIK_EMAIL__PORT:-587}
  username: ${AUTHENTIK_EMAIL__USER:-}
  password: ${AUTHENTIK_EMAIL__PASSWORD:-}
  use_tls: ${AUTHENTIK_EMAIL__USE_TLS:-true}
  use_ssl: ${AUTHENTIK_EMAIL__USE_SSL:-false}
  timeout: ${AUTHENTIK_EMAIL__TIMEOUT:-10}
  from: ${AUTHENTIK_EMAIL__FROM:-authentik@localhost}

# Configuración de medios y archivos estáticos
media:
  backend: ${AUTHENTIK_MEDIA_BACKEND:-file}
  file:
    path: ${AUTHENTIK_MEDIA_FILE_PATH:-/media}
  s3:
    access_key_id: ${AUTHENTIK_MEDIA_S3_ACCESS_KEY_ID:-}
    secret_access_key: ${AUTHENTIK_MEDIA_S3_SECRET_ACCESS_KEY:-}
    bucket_name: ${AUTHENTIK_MEDIA_S3_BUCKET_NAME:-}
    region: ${AUTHENTIK_MEDIA_S3_REGION:-us-east-1}
    custom_domain: ${AUTHENTIK_MEDIA_S3_CUSTOM_DOMAIN:-}
    endpoint: ${AUTHENTIK_MEDIA_S3_ENDPOINT:-}

# Configuración de outposts
outposts:
  # Docker socket para crear outposts automáticamente
  docker_socket: ${AUTHENTIK_OUTPOSTS_DOCKER_SOCKET:-unix:///var/run/docker.sock}
  docker_network: ${AUTHENTIK_OUTPOSTS_DOCKER_NETWORK:-nooble-network}
  
  # Configuración del outpost integrado
  builtin:
    enabled: true

# Configuración de seguridad
security:
  # Duración de las sesiones
  session_cookie_age: 604800  # 7 días en segundos
  
  # Configuración CSRF
  csrf_cookie_secure: true
  csrf_cookie_httponly: true
  
  # Configuración de cookies
  cookie_domain: ".nooble.local"
  
  # Headers de seguridad
  secure_proxy_ssl_header: ["HTTP_X_FORWARDED_PROTO", "https"]

# Configuración de la interfaz web
web:
  # URL pública de Authentik
  external_url: "https://auth.nooble.local"
  
  # Configuración de CORS
  cors_allowed_origins:
    - "https://nooble.local"
    - "https://app.nooble.local"
    - "http://localhost:3000"  # Para desarrollo

# Configuración de autenticación
authentication:
  # Duración del token
  token_expiry: 3600  # 1 hora
  
  # Configuración de contraseñas
  password_min_length: 8
  password_required_uppercase: true
  password_required_lowercase: true
  password_required_numeric: true
  password_required_special: true

# Configuración de logging
logging:
  level: "INFO"
  
  # Handlers de logging
  handlers:
    console:
      class: "logging.StreamHandler"
      formatter: "json"
    
    file:
      class: "logging.handlers.RotatingFileHandler"
      filename: "/var/log/authentik/authentik.log"
      maxBytes: 10485760  # 10MB
      backupCount: 5
      formatter: "json"

# Configuración de flows predeterminados
flows:
  # Flow de autenticación predeterminado
  default_authentication: "default-authentication-flow"
  
  # Flow de invalidación predeterminado
  default_invalidation: "default-invalidation-flow"
  
  # Flow de recuperación de contraseña
  default_recovery: "default-recovery-flow"
  
  # Flow de registro de usuarios
  default_enrollment: "default-enrollment-flow"
  
  # Flow de configuración de usuario
  default_user_settings: "default-user-settings-flow"

# Configuración de blueprints (plantillas de configuración)
blueprints:
  # Ruta donde se encuentran los blueprints personalizados
  paths:
    - "/blueprints/custom"
    - "/blueprints/default"

# Configuración de workers
workers:
  # Número de workers web
  web: 4
  
  # Configuración de Celery
  celery:
    # Número de workers de Celery
    worker_concurrency: 2
    
    # Configuración de beat (tareas programadas)
    beat_schedule:
      # Limpieza de tokens expirados
      clean_expired_tokens:
        task: "authentik.core.tasks.clean_expired_tokens"
        schedule: 3600  # Cada hora
      
      # Limpieza de sesiones expiradas
      clean_expired_sessions:
        task: "authentik.core.tasks.clean_expired_sessions"
        schedule: 86400  # Cada día

# Configuración de métricas
metrics:
  enabled: true
  port: 9300

# Configuración de avatares
avatars:
  # Fuentes de avatares
  sources:
    - gravatar
    - initials

# Footer personalizado (opcional)
footer_links:
  - name: "Documentation"
    href: "https://docs.nooble.com"
  - name: "Support"
    href: "https://support.nooble.com"

# Configuración de la marca
branding:
  title: "Nooble Authentication"
  logo: "/static/dist/assets/icons/icon.svg"
  favicon: "/static/dist/assets/icons/icon.png"